version: '3.5'

services:
  hello-api:
    build:
      context: .
      dockerfile: hello/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - ./etc:/app/etc
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"