name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 在服务器拉取代码，重新编译并重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_SECRET }}
          script: ｜
            cd ~/github-actions-test 
            git pull
            systemctl stop github-actions-test
            go mod tidy
            go build main.go
            systemctl start github-actions-test
            systemctl status github-actions-test


#      - name: Webhook
#        run: |
#          curl ${{ secrets.WEBHOOK_URL }}


#jobs:
#    build:
#        name: Build
#        runs-on: ubuntu-latest
#        steps:
#        - name: load Go 1.18 env
#          uses: actions/setup-go@v3
#          with:
#              go-version: '1.19'
#              cache: true
#
#
#        - name: checkout
#          uses: actions/checkout@v3

