name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        run: |
          curl ${{ secrets.WEBHOOK_URL }}


#jobs:
#    build:
#        name: Build
#        runs-on: ubuntu-latest
#        steps:
#        - name: load Go 1.18 env
#          uses: actions/setup-go@v3
#          with:
#              go-version: '1.19'
#              cache: true
#
#
#        - name: checkout
#          uses: actions/checkout@v3

