name: Build
on:
  push:
    branch:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true



      - name: Build
        run: go build main.go

      - name: Deploy
        env:
          SSH_USERNAME: ${{ secrets.DEPLOY_USER }}
          SSH_PASSWORD: ${{ secrets.DEPLOY_SECRET }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

        run: |
          # Stop the service
          #sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$DEPLOY_HOST -p $SSH_PORT "systemctl stop github-actions-test && rm -rf $DEPLOY_PATH/main"
          
          # Copy the binary to the remote server
          sshpass -p $SSH_PASSWORD scp -P 47 main root@www.nickxu.top:/root/github-actions-test
          
          # Restart the service on the remote server
          #sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$DEPLOY_HOST -p $SSH_PORT "systemctl start github-actions-test"

#name: Build
#on:
#  push:
#    branches:
#      - v2
#jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: 编译
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USER }}
#          password: ${{ secrets.DEPLOY_SECRET }}
#          script: cd ~/github-actions-test && git pull && bash run.sh




#      - name: Webhook
#        run: |
#          curl ${{ secrets.WEBHOOK_URL }}


#jobs:
#    build:
#        name: Build
#        runs-on: ubuntu-latest
#        steps:
#        - name: load Go 1.18 env
#          uses: actions/setup-go@v3
#          with:
#              go-version: '1.19'
#              cache: true
#
#
#        - name: checkout
#          uses: actions/checkout@v3

